// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkHPDjr4BRrKO-XNAly_I9Jwpm_Nd08NQ',
    appId: '1:707532126208:web:e6d3bf94b02270aa5900e5',
    messagingSenderId: '707532126208',
    projectId: 'csen268-omniwallet',
    authDomain: 'csen268-omniwallet.firebaseapp.com',
    storageBucket: 'csen268-omniwallet.firebasestorage.app',
    measurementId: 'G-Q337N36N5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV-G4Fy1PMJM3dyEHH-rMDNTtjm8crh6o',
    appId: '1:707532126208:android:68a9ef311e4df1a75900e5',
    messagingSenderId: '707532126208',
    projectId: 'csen268-omniwallet',
    storageBucket: 'csen268-omniwallet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3B3ARQK8YxEdGNFQvV8TS7YgXGAeBEwk',
    appId: '1:707532126208:ios:8a526f563338bc0f5900e5',
    messagingSenderId: '707532126208',
    projectId: 'csen268-omniwallet',
    storageBucket: 'csen268-omniwallet.firebasestorage.app',
    iosBundleId: 'com.csen268.omniwallet',
  );
}
